### ISSUE TITLE
Finding all files containing a text string with Command line or Vim.

### ISSUE THREAD

**Issue by samzeng** [cyberwizardinstitute/workshops#22]
Use grep command and edit in Vim again?
How does it work in this workflow, so curious.

**Comment by possibly** [comment]
What workshop are you referring to? Perhaps [this "Unix" workshop](https://github.com/cyberwizardinstitute/workshops/blob/master/unix.markdown)?

In that workshop I remember us using the `ls` command to list all of the files in the current directory, then piping the output of `ls` to `grep`.

So if `ls` outputs:
`Applications   Documents  Music Mu`

Then `ls | grep "Mu"` outputs:
```
Music 
Mu
```

**Comment by SamZeng** [comment]
@possibly Yeah, Unix, Screen and Vim. Coding workflow.

Vim does not install plugin, like ack, ag.
